config/routes.rb
Rails.application.routes.draw do
  # get 'public_recipes/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'shopping_list/recipe_id/:recipe_id/inventory_id/:inventory_id', to: 'shopping_lists#shopping_list', as: 'shopping_list'

  resources :inventories, only: [:index, :new, :show, :create, :update, :destroy] do
    resources :inventory_foods, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  root 'public_recipes#index'
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory, class_name: 'Inventory', foreign_key: 'inventory_id'
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :inventory_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :food_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
  before_action :set_inventory, only: [:destroy]
  def index; end

  def show; end

  def new
    @inventory = Inventory.find(params[:inventory_id])
    @foods = Food.all
    @inventory_food = InventoryFood.new
  end

  def create
    @inventory_food = InventoryFood.new(inventory_food_params)
    @inventory = Inventory.find(params[:inventory_id]) # Retrieve the associated inventory

    if @inventory_food.save
      flash[:notice] = 'Inventory created successfully.'
      redirect_to inventory_path(@inventory)
    else
      flash.now[:alert] = 'Inventory creation failed.'
      redirect_to new_inventory_url
    end
  end

  def destroy
    @inventory_food = InventoryFood.find(params[:id])
    @inventory_food.destroy

    flash[:notice] = 'Inventory Food was successfully deleted.'
    redirect_to inventory_path(@inventory)
  end

  private

  def inventory_food_params
    params.require(:inventory_food).permit(:quantity, :inventory_id, :food_id)
  end
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/views/inventory_foods/_new.html.erb
<%= form_with(model: @inventory_food, url: inventory_inventory_foods_path(@inventory), local: true, remote: true, id: 'inventory-food-form') do |form| %>
    <div class = "mt-4 p-2">
      <%= form.hidden_field :inventory_id, value: @inventory.id %>
      <%= form.collection_select :food_id, @foods, :id, :name, { prompt: '.. Select a Food ..' }, { id: 'food-select', class: 'form-control' } %>
      <% if @inventory_food.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <%= @inventory_food.errors[:food_id].first %>
        </div>
      <% end %>
    </div>
  
    <div class = "mt-2 p-2">
      <%= form.number_field :quantity,
          autofocus: true,
          autocomplete: 'quantity',
          placeholder: 'Enter quantity',
          class: 'form-control'
      %>
      <% if @inventory_food.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <%= @inventory_food.errors[:quantity].first %>
        </div>
      <% end %>
    </div>
  
    <div class="actions text-center mt-4">
      <%= form.submit 'Add', class: 'btn btn-primary btn-sm  px-4' %>
      <%= link_to 'Cancel', inventory_path(@inventory), class: "btn btn-dark btn-sm px-3" %>
    </div>
<% end %>

app/views/inventory_foods/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="mt-5 p-2 border shadow-lg bg-white rounded">
      <h4 class="text-center"><%= @inventory.name %></h4>
      <% unless @foods.empty? %>
        <%= render 'new' %>
      <% else %>
        <p class="text-center mt-4">
          No foods available. Please add a food first. <br>
          <%= link_to 'Add a Food', new_food_path, data: { turbo_frame: "remote_modal" } %>
        </p>
        <div class="actions text-end mt-4">
          <%= link_to 'Cancel', inventory_path(@inventory), class: "btn btn-dark btn-sm px-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>