config/routes.rb
Rails.application.routes.draw do
  # get 'public_recipes/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'shopping_list/recipe_id/:recipe_id/inventory_id/:inventory_id', to: 'shopping_lists#shopping_list', as: 'shopping_list'

  resources :inventories, only: [:index, :new, :show, :create, :update, :destroy] do
    resources :inventory_foods, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  root 'public_recipes#index'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :inventory_foods, class_name: 'InventoryFood', dependent: :destroy
  has_many :foods, through: :inventory_foods

  validates :user_id, :name, :description, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_inventory, only: [:destroy]

  def index
    @inventories = Inventory.includes(:inventory_foods).where(user_id: current_user.id)
  end

  def new
    @inventory = Inventory.new
    @foods = Food.all # Fetch a collection of all food items
    @inventory_food = InventoryFood.new
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def create
    @inventory = current_user.inventories.build(inventory_params)
    if @inventory.save
      flash[:notice] = 'Inventory created successfully.'
      redirect_to inventories_path
    else
      flash.now[:alert] = 'Inventory creation failed.'
      render :new # Render the 'new' view to show validation errors and preserve form data
    end
  end

  def destroy
    if can_manage_inventory?(@inventory)
      if @inventory.destroy
        flash[:notice] = 'Inventory deleted successfully.'
      else
        flash[:alert] = 'Error deleting the inventory.'
      end
    else
      flash[:alert] = 'You do not have permission to delete this inventory.'
    end

    redirect_to inventories_path
  end

  private

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end

  def can_manage_inventory?(inventory)
    inventory.user == current_user
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/index.html.erb
<h1 class="text-center py-3">Inventories List</h1>

<%= link_to "Add Inventory", new_inventory_path, class: "btn btn-primary mb-2 float-end" %>
<% @inventories.each do |inventory| %>
  <%= render partial: 'shared/inventory_card', locals: { inventory: inventory } %>
<% end %>

app/views/inventories/new.html.erb
<h3 class="text-center">Add New Inventory</h3>
<%= form_with(model: @inventory, local: true, class: 'form') do |form| %>
    <div class="form-group mt-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group mt-3">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control', rows: 4, cols: 50 %>
    </div>
    <%= form.submit "Add Inventory", class: "btn btn-primary mt-3" %>
<% end %>

app/views/inventories/show.html.erb
<div class="container-fluid">
    <div class="container mt-5"> 
        <h2 class="text-center"><%= @inventory.name %></h2>
        <div class="row">
            <div class="col-10 offset-1">
                <div class="text-align-left">
                    <%= link_to 'Add Food', new_inventory_inventory_food_path(@inventory), id: 'add-food-link', class: 'btn btn-primary float-end mb-3 p-2 text-decoration-none' %>                
                </div>
                <div class="table">
                <% if @inventory.inventory_foods.any? %>
                <table class="table table-striped table-bordered mt-2">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Food</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @inventory.inventory_foods.each_with_index do |food_inventory, index| %>
                      <tr>
                        <td><%= index + 1 %></td>                   
                        <td><%=food_inventory.food.name %></td>
                        <td>
                          <%= food_inventory.quantity.to_i %>
                          <%= food_inventory.food.measurement_unit %>
                        </td>
                        <td class="d-flex justify-content-center justify-content-around">
                          <% if can? :manage, @inventory %>
                            <%= button_to "Remove", inventory_inventory_food_path(@inventory, food_inventory), class: "btn btn-danger", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
                          <% else %>
                            NA
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              <% end %>
                </div>
            </div>
        </div>
    </div>
</div>