config/routes.rb
Rails.application.routes.draw do
  # get 'public_recipes/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'shopping_list/recipe_id/:recipe_id/inventory_id/:inventory_id', to: 'shopping_lists#shopping_list', as: 'shopping_list'

  resources :inventories, only: [:index, :new, :show, :create, :update, :destroy] do
    resources :inventory_foods, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  root 'public_recipes#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :destroy
  has_many :foods, through: :recipe_foods

  attribute :public, :boolean, default: false

  validates :user_id, :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include RecipesHelper
  load_and_authorize_resource
  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(new_recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      # Handle successful update
      redirect_to @recipe, notice: 'Recipe updated successfully'
    else
      # Handle validation errors
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize! :destroy, @recipe
    if @recipe.destroy
      flash[:notice] = 'Recipe was successfully deleted.'
    else
      flash[:alert] = 'Error deleting the recipe.'
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:public)
  end

  def new_recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def recipe_total_amount(recipe)
    total_amount = 0

    recipe.recipe_foods.each do |recipe_food|
      total_amount += recipe_food.quantity * recipe_food.food.price
    end

    total_amount
  end
end

app/views/recipes/index.html.erb
<h1 class="text-center py-4">Recipes list</h1>

<%= link_to "Add New Recipe", new_recipe_path, class: "btn btn-primary mb-2 float-end" %>
<!-- ... (previous code) -->

<% @recipes.each do |recipe| %>
  <div class="card border-secondary mb-2" style="width: 100%;">
    <div class="card-body text-secondary d-flex justify-content-between align-items-center">
      <div style="width: 30%;">
        <h5 class="card-title">
          <a href="<%= recipe_path(recipe) %>" class="text-decoration-none text-uppercase font-weight-bold">
            <%= recipe.name %>
          </a>
        </h5>
        <%= button_to "REMOVE", recipe_path(recipe), method: :delete, data: { turbo_confirm: "Are you sure? "}, class: "text-decoration-none btn btn-danger" %>
      </div>

      <p style="width: 70%;"><%= recipe.description %></p>

      <!-- Display quantities of associated foods without the food name -->
      <p>Quantities: <%= recipe.recipe_foods.pluck(:quantity).join(', ') %></p>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1 class="text-center py-3">Add New Recipe</h1>

<%= form_for @recipe do |f| %>
  <div class="form-group my-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :preparation_time %>
    <%= f.text_field :preparation_time, class: "form-control" %>
  </div>

  <div class="form-group my-3">
    <%= f.label :cooking_time %>
    <%= f.text_field :cooking_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group form-check">
    <%= f.check_box :public, class: "form-check-input" %>
    <%= f.label :public, class: "form-check-label" %>
  </div>

  <div class="actions">
    <%= f.submit "Add Recipe", class: "btn btn-primary my-3" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<h1 class="text-center py-4"><%= @recipe.name.upcase %></h1>
<div class="d-flex justify-content-between">
  <div>
    <p class="lead">Preparation time: <span><%= @recipe.preparation_time %></span></p>
    <p class="lead">Cooking time :<span><%= @recipe.cooking_time %></span></p>
    <p class="lead"><%= @recipe.description %></p>
  </div>
  <div class="d-flex">
    <% if @recipe.user == current_user %>
      <p class="mr-4 m-2"><%= @recipe.public ? 'Pulic' : 'Private' %></p>
      <%= form_for @recipe, url: recipe_path(@recipe), method: :patch, html: {id: 'recipe-form' } do |f| %>
        <div class="toggle form-check form-switch m-2">
          <%= f.check_box :public, { id: 'public-checkbox', class: 'form-check-input', onchange: 'this.form.submit();' } %>
        </div>
      <% end %>
    <%end%>
  </div>
</div>

<div class="d-flex justify-content-between mt-5">
  <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Generate shopping list
  </button>
  <button type="button" class="btn btn-primary">
    <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: "text-white text-decoration-none" %>
  </button>
</div>

<hr>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Value per Unit</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @recipe.recipe_foods.each do |recipe_food| %>
    <tr>
      <td><%= recipe_food.food.name %></td>
      <td><%= recipe_food.quantity %></td>
      <td>$ <%= recipe_food.food.price %></td>
      <td>
        <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food), class: "btn btn-info text-white" %>
        <%= form_with(model: [@recipe, recipe_food], local: true, method: :delete, data: { confirm: "Are you sure?" }) do |form| %>
          <%= form.submit "Delete", class: "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title fs-5" id="exampleModalLabel">Generate Shopping List</h2>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(url: shopping_list_path(recipe_id: @recipe.id, inventory_id: :selected_inventory_id), method: :get) do |form| %>
          <div class="form-group">
            <%= form.collection_select :selected_inventory_id, current_user.inventories, :id, :name, { prompt: '.. Select an Inventory ..' }, { id: 'inventory-select', class: 'form-control' } %>
          </div>
          <div class="form-group mt-3">
            <%= form.submit "Generate", class: "btn btn-primary" %>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
  </div>
</div>