config/routes.rb
Rails.application.routes.draw do
  # get 'public_recipes/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'shopping_list/recipe_id/:recipe_id/inventory_id/:inventory_id', to: 'shopping_lists#shopping_list', as: 'shopping_list'

  resources :inventories, only: [:index, :new, :show, :create, :update, :destroy] do
    resources :inventory_foods, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  root 'public_recipes#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg text-white bg-primary">
      <div class="container-fluid">
        <span><%= link_to 'Recipe App', root_path, class: "nav-link" %></span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>

            <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Add Food', new_food_path, class: "nav-link text-white" %>
            </li>
            
            <li class="nav-item">
              <%= link_to 'Recipes', recipes_path, class: "nav-link text-white"%>
            </li>
            <li>
              <%= link_to 'Inventories', inventories_path, class: "nav-link text-white" %>
            </li>
            <li>
              <%= link_to 'Public Recipes', root_path, class: "nav-link text-white" %>
            </li>
            <li class="d-flex align-items-center">
              <%= button_to "LogOut", destroy_user_session_path, method: :delete, class: "btn btn-outline-light btn-sm" %>
              <% else %>
              <li>
              <%= link_to 'Sign Up', new_user_registration_path , class: "nav-link text-white"%>
              </li>
              <li>
              <%= link_to 'Log In', new_user_session_path,  class: "nav-link text-white"%>
              </li>
            <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container wrapper d-flex flex-column min-vh-100">
      <div class="row d-flex justify-content-center align-items-center">
        <div class="col-9">

          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

          <%= yield %>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>